version: '3.8'

services:
  c1:
    build: ./c1
    container_name: c1
    tty: true # mantiene el contenedor corriendo
    networks:
      - lab-ssh-net

  c2:
    build: ./c2
    container_name: c2
    tty: true # mantiene el contenedor corriendo
    networks:
      - lab-ssh-net

  c3:
    build: ./c3
    container_name: c3
    tty: true # mantiene el contenedor corriendo
    networks:
      - lab-ssh-net

  s1: # Este contenedor es C4 y S1 
    build: ./c4
    container_name: s1
    hostname: s1
    tty: true # mantiene el contenedor corriendo
    networks:
      - lab-ssh-net

networks:
  lab-ssh-net:
    driver: bridge